# NOAA Station Info
noaa:
  station_id: "8534720" # Atlantic City Station ID
  buoy_id: "44091" # Barnegat Buoy ID

# Email Settings
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}
  recipient: ${EMAIL_RECIPIENT}
  test_recipients: ${TEST_RECIPIENTS} # Optional for testing

# Location Coordinates
location:
  longitude: ${LONGITUDE}
  latitude: ${LATITUDE}
