# NOAA Station Info
noaa:
  station_id: "8534720" # Atlantic City Station ID
  buoy_id: "44091" # Barnegat Buoy ID

# Email Settings
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}
  recipients: ${EMAIL_RECIPIENTS}
  test_recipients: ${TEST_RECIPIENTS} # Optional for testing
  recipient_urls:
    main: ${RECIPIENTS_GIST_URL}
    test: ${TEST_RECIPIENTS_GIST_URL}
    offseason: ${OFFSEASON_RECIPIENTS_GIST_URL}

# Location Coordinates
location:
  longitude: ${LONGITUDE}
  latitude: ${LATITUDE}
  beach_orientation_degrees: 140 # ${BEACH_ORIENTATION_DEGREES}
