name: Daily Water Report

on:
  schedule:
    # What Time does it run? 
    # 10:35am UTC (6:35am Eastern Time, 3:35am Pacific Time)
    # 09:50am UTC (5:50am Eastern Time, 2:50am Pacific Time)
    - cron: "17 08 * * *"
  workflow_dispatch:

concurrency:
  group: water-report
  cancel-in-progress: true

jobs:
  run-water-report:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run water report
        env:
          # Environment
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LATITUDE: ${{ secrets.LATITUDE }}
          BEACH_ORIENTATION_DEGREES: ${{ secrets.BEACH_ORIENTATION_DEGREES || '140' }}

          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          BCC_URL: ${{ secrets.BCC_URL }}
          TEST_RECIPIENTS: ${{ secrets.TEST_RECIPIENTS }}

          RECIPIENTS_GIST_URL: ${{ secrets.RECIPIENTS_GIST_URL }}
          TEST_RECIPIENTS_GIST_URL: ${{ secrets.TEST_RECIPIENTS_GIST_URL }}
          OFFSEASON_RECIPIENTS_GIST_URL: ${{ secrets.OFFSEASON_RECIPIENTS_GIST_URL }}

          RUN_EMAIL: "true"
          TEST: "false"

        run: python scripts/run-report.py
