name: Daily Water Report

on:
  schedule:
    - cron: "0 11 * * *" # Runs daily at 11:00 UTC (7:00 AM US Eastern)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-water-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # this installs from the root pyproject.toml

      - name: Run water report
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python -m lbi_surf.main
