name: Test Daily Water Report

on:
  workflow_dispatch: # Manual trigger only

jobs:
  run-water-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # install lbi_surf from source

      - name: Run custom water report
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          BCC_URL: ${{ secrets.BCC_URL }}
          TEST_RECIPIENTS: ${{ secrets.TEST_RECIPIENTS }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LATITUDE: ${{ secrets.LATITUDE }}
          RECIPIENTS_GIST_URL: ${{ secrets.RECIPIENTS_GIST_URL }}
          TEST_RECIPIENTS_GIST_URL: ${{ secrets.TEST_RECIPIENTS_GIST_URL }}

        run: |
          python -c "import lbi_surf; lbi_surf.hello(); lbi_surf.main(run_email=True, test=True)"
      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Error occurred while running the water report."
            exit 1
          else
            echo "Water report ran successfully."
          fi
